import { RawUserData } from "./IRawUserData";
import { OverwriteData } from "./IOverwriteData";
import { Snowflake } from "../types/Snowflake";
import { ChannelTypes } from "../props/ChannelTypes";
import { DefaultReactionEmoji } from "./IDefaultReactionEmoji";
import { GuildForumChannelTag } from "./IGuildForumChannelTag";

export interface GuildChannelData {
    id: Snowflake;
    type: ChannelTypes;
    guild_id?: Snowflake;
    position?: number;
    permission_overwrites?: OverwriteData[];
    name?: string;
    topic?: string;
    nsfw?: boolean;
    last_message_id?: Snowflake;
    bitrate?: number;
    user_limit?: number;
    rate_limit_per_user?: number;
    recipients?: RawUserData[];
    icon?: string;
    managed?: boolean;
    parent_id?: Snowflake;
    last_pin_timestamp?: number;
    rtc_region?: string;
    video_quality_mode?: number;
    message_count?: number;
    member_count?: number;
    default_auto_archive_duration?: number;
    permissions?: string;
    flags?: number;
    total_message_sent?: number;
    available_tags?: GuildForumChannelTag[];
    applied_tags?: string[];
    default_reaction_emoji?: DefaultReactionEmoji;
    default_thread_rate_limit_per_user?: number;
    default_sort_order?: number;
    default_forum_layout?: number;
};