import { RawUserData } from "./IRawUserData";
import { EmbedData } from "./IEmbedData";
import { GuildChannelData } from "./IGuildChannelData";
import { RawGuildStickerData } from "./IRawGuildStickerData";
import { RawReactionEmoji } from "./IRawReactionEmoji";
import { ActionRowData } from "./IActionRowData";
import { AttachmentData } from "./IAttachmentData";
import { IApplication } from "./IApplication";
import { Snowflake } from "../types/Snowflake";
import { ChannelMention } from "./IChannelMention";
import { MessageTypes } from "../props/MessageTypes";
import { MessageActivity } from './IMessageActivity';
import { RawMessageReference } from "./IRawMessageReference";
import { RawMessageInteractionData } from "./IRawMessageInteractionData";
import { GuildRoleSubscriptionData } from "./IGuildRoleSubscriptionData";
import { RawGuildData } from "./IRawGuildData";

export interface IMessage {
    id: Snowflake;
    guild: RawGuildData;
    channel: GuildChannelData;
    author: RawUserData;
    content?: string;
    timestamp: number;
    edited_timestamp?: number;
    tts: boolean;
    mention_everyone: boolean;
    mentions: RawUserData[];
    mention_roles: string[];
    mention_channels?: ChannelMention[];
    attachments?: AttachmentData[];
    embeds: EmbedData[];
    reactions?: RawReactionEmoji[];
    nonce?: string | number;
    pinned: boolean;
    webhook_id?: Snowflake;
    type: MessageTypes;
    activity?: MessageActivity;
    application?: IApplication;
    application_id?: Snowflake;
    message_reference?: RawMessageReference;
    flags?: number;
    referenced_message?: IMessage;
    interaction?: RawMessageInteractionData;
    thread?: GuildChannelData;
    components?: ActionRowData[];
    sticker_items?: Pick<RawGuildStickerData, 'id' | 'name' | 'format_type'>[];
    stickers: RawGuildStickerData[];
    position?: number;
    role_subscription_data?: GuildRoleSubscriptionData;
};