import { Snowflake } from "../types/Snowflake";
import { RawWelcomeScreenData } from "./IRawWelcomeScreenData";
import { GuildRoleManager } from "../managers/GuildRoleManager";
import { GuildEmojiManager } from "../managers/GuildEmojiManager";
import { GuildMemberManager } from "../managers/GuildMemberManager";
import { ChannelManager } from "../managers/ChannelManager";
import { GuildStickerManager } from "../managers/GuildStickerManager";

export interface GuildData {
    id: Snowflake;
    name: string;
    icon?: string;
    icon_hash?: string;
    splash?: string;
    discovery_splash?: string;
    owner_id: Snowflake;
    region?: string;
    afk_channel_id?: Snowflake;
    afk_timeout: number;
    widget_enabled: boolean;
    widget_channel_id?: Snowflake;
    verification_level: number;
    default_message_notifications: number;
    explicit_content_filter: number;
    roles: GuildRoleManager;
    emojis: GuildEmojiManager;
    channels: ChannelManager;
    members: GuildMemberManager;
    features: string[];
    mfa_level: number;
    application_id?: Snowflake;
    system_channel_id?: Snowflake;
    system_channel_flags: number;
    rules_channel_id?: Snowflake;
    max_presences?: number;
    max_members: number;
    vanity_url_code?: string;
    description?: string;
    banner?: string;
    premium_tier: number;
    premium_subscription_count?: number;
    preferred_locale: string;
    public_updates_channel_id?: Snowflake;
    max_video_channel_users?: number;
    approximate_member_count?: number;
    welcome_screen?: RawWelcomeScreenData;
    nsfw_lever: number;
    stickers?: GuildStickerManager;
    premium_progress_bar_enabled: boolean;
};