import { Snowflake } from "../types/Snowflake";
import { GuildRoleData } from "./IGuildRoleData";
import { RawGuildEmoji } from "./IRawGuildEmoji";
import { RawGuildStickerData } from "./IRawGuildStickerData";
import { RawWelcomeScreenData } from "./IRawWelcomeScreenData";

export interface RawGuild {
    id: Snowflake;
    name: string;
    icon?: string;
    icon_hash?: string;
    splash?: string;
    discovery_splash?: string;
    owner_id: Snowflake;
    region?: string;
    afk_channel_id?: Snowflake;
    afk_timeout: number;
    widget_enabled?: boolean;
    widget_channel_id?: Snowflake;
    verification_level: number;
    default_message_notifications: number;
    explicit_content_filter: number;
    roles: GuildRoleData[];
    emojis: RawGuildEmoji[];
    features: string[];
    mfa_level: number;
    application_id?: Snowflake;
    system_channel_id?: Snowflake;
    system_channel_flags: number;
    rules_channel_id?: Snowflake;
    max_presences?: number;
    max_members?: number;
    vanity_url_code?: string;
    description?: string;
    banner?: string;
    premium_tier: number;
    premium_subscription_count?: number;
    preferred_locale: string;
    public_updates_channel_id?: Snowflake;
    max_video_channel_users?: number;
    max_stage_video_channel_users?: number;
    approximate_member_count?: number;
    approximate_presence_count?: number;
    welcome_screen?: RawWelcomeScreenData;
    nsfw_level: number;
    stickers?: RawGuildStickerData[];
    premium_progress_bar_enabled: boolean;
};