export interface IEditGuildOptions {
    name?: string,
    verification_level?: number,
    default_message_notifications?: number,
    explicit_content_filter?: number,
    afk_channel_id?: string,
    afk_timeout?: number,
    icon?: string,
    owner_id?: string,
    splash?: string,
    discovery_splash?: string,
    banner?: string,
    system_channel_id?: string,
    system_channel_flags?: number,
    rules_channel_id?: string,
    public_updates_channel_id?: string,
    preferred_locale?: string,
    features?: string[],
    description?: string,
    premium_progress_bar_enabled?: boolean
};